### ISSUE TITLE
Wrong var ref scripts/helpers/register-sgx

### ISSUE THREAD

**Issue by 0xm51** [lagunovsky/simple-raiko-node#1]
Hi, thx for this great tool :)

I assume the this var ref is wrong in `scripts/helpers/register-sgx` (line 9)

```
    --fork-url ${L1_RPC} \
```

should be 

```
    --fork-url ${FORK_URL} \
```

Or it fails during registration

**Comment by lagunovsky** [comment]
Thanks, fixed
